// generate-config.js — runs as Vercel build command
// Reads environment variables and writes config.js so the static HTML pages
// can access Airtable credentials without them ever being in source control.

const fs = require("fs");

const key    = process.env.AIRTABLE_API_KEY;
const baseId = process.env.AIRTABLE_BASE_ID;

if (!key || !baseId) {
  console.error("❌  Missing env vars: AIRTABLE_API_KEY and/or AIRTABLE_BASE_ID");
  console.error("   Set them in Vercel Dashboard → Project → Settings → Environment Variables");
  process.exit(1);
}

const content = `// ⚠ Auto-generated by generate-config.js — do not edit manually
window.DKM_CONFIG = {
  AIRTABLE_API_KEY: "${key}",
  BASE_ID:          "${baseId}",
  TABLE_NAME:       "Employees"
};
`;

fs.writeFileSync("config.js", content, "utf8");
console.log("✅  config.js generated successfully");
